version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: flask_demo
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flask_demo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
volumes:
  postgres_data:
